import { ArrowUpRight, Check, CircleDot, GitCommitHorizontal, Wrench } from "lucide-react";

const entries = [
  { id: "NOW", title: "The first board takes shape", copy: "Routing the dual-MCU core and working out how much goblin can fit around a 40-pin FPC without making the antenna geometry sad.", state: "in-progress" },
  { id: "01", title: "Power tree / USB-C to buck", copy: "The 1500 mAh LiPo path is mapped: USB-C charge, protection, and a clean buck stage for the modules.", state: "done" },
  { id: "00", title: "The idea gets a face", copy: "A pixelated goblin on silkscreen. Antenna ears. A display in the forehead. The shape started as a joke and survived the block diagram.", state: "done" },
];

export default function BuildLog() { return <div className="page"><section className="page-hero page-hero-short"><div className="container"><div className="eyebrow"><span className="pulse-dot" /> FIELD NOTES / PUBLIC BUILD</div><h1>Making the<br /><em>first one.</em></h1><p>Short notes from the bench as Signal Goblin moves from pinout to prototype.</p></div></section><section className="section log-section"><div className="container log-layout"><aside className="log-aside"><div className="section-kicker">/ STATUS</div><div className="status-card"><span className="status-big">0.1</span><span>prototype<br />in progress</span><div className="progress-track"><div /></div><small>SCHEMATIC → PCB</small></div><a className="text-link" href="https://github.com" target="_blank" rel="noreferrer">Watch on GitHub <ArrowUpRight size={15} /></a></aside><div className="timeline">{entries.map(({ id, title, copy, state }) => <article className="log-entry" key={id}><div className={state === "in-progress" ? "timeline-dot current" : "timeline-dot"}>{state === "done" ? <Check size={13} /> : <CircleDot size={13} />}</div><div className="log-content"><div className="log-meta"><span>{id}</span><span>{state === "in-progress" ? "in progress" : "complete"}</span></div><h2>{title}</h2><p>{copy}</p><div className="log-tag">{state === "done" ? <GitCommitHorizontal size={14} /> : <Wrench size={14} />} {state === "done" ? "checkpoint" : "on the bench"}</div></div></article>)}</div></div></section></div>; }
