import { ArrowDownToLine, FileCode2, FolderArchive, Github, Package } from "lucide-react";

const files: { name: string; detail: string; status: string; Icon: typeof FileCode2 }[] = [
  { name: "signal-goblin-firmware", detail: "Firmware source / alpha", status: "Coming soon", Icon: FileCode2 },
  { name: "signal-goblin-pcb", detail: "Schematic + PCB project", status: "Coming soon", Icon: Package },
  { name: "signal-goblin-site", detail: "This website / source", status: "Available", Icon: FolderArchive },
];

export default function Downloads() { return <div className="page"><section className="page-hero page-hero-short"><div className="container"><div className="eyebrow"><span className="pulse-dot" /> ARCHIVE / TAKE IT APART</div><h1>Files for<br /><em>curious hands.</em></h1><p>Firmware, board files, and build notes will land here as the prototype gets real.</p></div></section><section className="section download-section"><div className="container download-layout"><div><div className="section-kicker">/ THE TOOLBOX</div><h2>Take the<br /><span className="text-green">goblin home.</span></h2><p className="muted-copy">Everything is being built in public. Right now the site is the first artifact; hardware and firmware follow when they are ready to share.</p><a className="button button-outline" href="https://github.com" target="_blank" rel="noreferrer"><Github size={16} /> View repository <span>↗</span></a></div><div className="file-list">{files.map(({ name, detail, status, Icon }) => <div className="file-row" key={name}><div className="file-icon"><Icon size={19} /></div><div className="file-info"><strong>{name}</strong><span>{detail}</span></div><div className={status === "Available" ? "file-status available" : "file-status"}>{status}</div>{status === "Available" ? <ArrowDownToLine size={17} /> : <span className="file-lock">—</span>}</div>)}</div></div></section><section className="terminal-section"><div className="container"><div className="terminal-window"><div className="terminal-top"><span>goblin@bench:~</span><span>● ● ●</span></div><div className="terminal-body"><div><span className="terminal-green">$</span> git clone github.com/signal-goblin/firmware</div><div className="terminal-dim">Cloning into 'firmware'...</div><div className="terminal-green">coming soon<span className="cursor">_</span></div></div></div></div></section></div>; }
